// Interactive trivia questions for the appraisal loading screen
// Each question tests knowledge about collectibles, antiques, and valuables

export interface TriviaQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
  category: 'books' | 'toys' | 'tech' | 'art' | 'coins' | 'fashion' | 'general' | 'watches' | 'sports' | 'music';
  difficulty: 'easy' | 'medium' | 'hard';
  points: number; // Points awarded for correct answer
}

export const triviaQuestions: TriviaQuestion[] = [
  // ============================================
  // BOOKS & LITERATURE (15 questions)
  // ============================================
  {
    id: 'book-1',
    question: 'A first edition Harry Potter book sold at auction for approximately:',
    options: ['$47,000', '$471,000', '$4,700', '$1.2 million'],
    correctIndex: 1,
    explanation: 'A first edition Harry Potter and the Philosopher\'s Stone sold for $471,000! Only 500 copies were printed in the first run.',
    category: 'books',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'book-2',
    question: 'Which comic book holds the record for highest sale price?',
    options: ['Batman #1', 'Action Comics #1 (Superman)', 'Amazing Fantasy #15 (Spider-Man)', 'X-Men #1'],
    correctIndex: 1,
    explanation: 'Action Comics #1, featuring Superman\'s first appearance, sold for $3.25 million - the most expensive comic ever!',
    category: 'books',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'book-3',
    question: 'Vintage Dr. Seuss books from the 1950s can be worth up to:',
    options: ['$500', '$2,000', '$20,000', '$100,000'],
    correctIndex: 2,
    explanation: 'Early Dr. Seuss first editions, especially "The Cat in the Hat" and "How the Grinch Stole Christmas," can fetch $4,000-$20,000!',
    category: 'books',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'book-4',
    question: 'A first edition of "The Great Gatsby" from 1925 is worth approximately:',
    options: ['$5,000-$10,000', '$25,000-$50,000', '$100,000-$150,000', '$500,000+'],
    correctIndex: 2,
    explanation: 'First edition copies of The Great Gatsby in good condition regularly sell for $100,000-$150,000 at auction.',
    category: 'books',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'book-5',
    question: 'The first issue of "Detective Comics" featuring Batman sold for:',
    options: ['$500,000', '$1 million', '$1.5 million', '$2.2 million'],
    correctIndex: 2,
    explanation: 'Detective Comics #27 (first Batman appearance) sold for $1.5 million, making it one of the most valuable comics.',
    category: 'books',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'book-6',
    question: 'A first edition "To Kill a Mockingbird" signed by Harper Lee is worth:',
    options: ['$5,000-$10,000', '$20,000-$45,000', '$50,000-$100,000', '$200,000+'],
    correctIndex: 1,
    explanation: 'Signed first editions of To Kill a Mockingbird typically sell for $20,000-$45,000 depending on condition.',
    category: 'books',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'book-7',
    question: 'What makes a book a "true first edition"?',
    options: ['First year printed', 'First printing of first edition', 'Signed by author', 'Hardcover only'],
    correctIndex: 1,
    explanation: 'A true first edition is the first printing of the first edition - subsequent printings are less valuable.',
    category: 'books',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'book-8',
    question: 'Vintage Nancy Drew books from the 1930s can be worth:',
    options: ['$20-$50', '$100-$500', '$500-$5,000', '$10,000+'],
    correctIndex: 2,
    explanation: 'Early Nancy Drew books with dust jackets from the 1930s can sell for $500-$5,000 to collectors!',
    category: 'books',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'book-9',
    question: 'The Gutenberg Bible, one of the first printed books, is valued at:',
    options: ['$5 million', '$15 million', '$25-35 million', '$100 million+'],
    correctIndex: 2,
    explanation: 'Complete Gutenberg Bibles are valued at $25-35 million. Only 49 copies survive today.',
    category: 'books',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'book-10',
    question: 'A first edition "The Hobbit" from 1937 in good condition sells for:',
    options: ['$5,000-$10,000', '$30,000-$70,000', '$100,000-$300,000', '$500,000+'],
    correctIndex: 2,
    explanation: 'First edition Hobbit books from 1937 regularly sell for $100,000-$300,000. Only 1,500 were printed!',
    category: 'books',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'book-11',
    question: 'What\'s the most valuable children\'s book ever sold?',
    options: ['Charlotte\'s Web', 'Where the Wild Things Are', 'Alice in Wonderland', 'The Tale of Peter Rabbit'],
    correctIndex: 2,
    explanation: 'A first edition Alice in Wonderland (1865) sold for $1.5 million - the most valuable children\'s book.',
    category: 'books',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'book-12',
    question: 'Stephen King\'s first novel "Carrie" (1974) first edition is worth:',
    options: ['$500-$1,000', '$2,000-$5,000', '$7,000-$15,000', '$50,000+'],
    correctIndex: 2,
    explanation: 'First edition copies of Carrie in dust jacket sell for $7,000-$15,000. It was his debut novel!',
    category: 'books',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'book-13',
    question: 'What dramatically increases a book\'s value?',
    options: ['Number of pages', 'Original dust jacket', 'Publisher location', 'Paper quality'],
    correctIndex: 1,
    explanation: 'The original dust jacket can increase a book\'s value by 10x or more! Many collectors require it.',
    category: 'books',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'book-14',
    question: 'A complete set of original Hardy Boys books is worth:',
    options: ['$100-$300', '$500-$2,000', '$3,000-$10,000', '$20,000+'],
    correctIndex: 2,
    explanation: 'Complete original Hardy Boys sets from the 1920s-30s with dust jackets can fetch $3,000-$10,000.',
    category: 'books',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'book-15',
    question: 'Which author\'s signature adds the most value to their books?',
    options: ['J.K. Rowling', 'J.D. Salinger', 'Stephen King', 'Dan Brown'],
    correctIndex: 1,
    explanation: 'J.D. Salinger rarely signed books, making his signature extremely rare and valuable - adding $50,000+!',
    category: 'books',
    difficulty: 'hard',
    points: 15,
  },

  // ============================================
  // TOYS & COLLECTIBLES (15 questions)
  // ============================================
  {
    id: 'toy-1',
    question: 'An original 1959 Barbie doll in good condition is worth approximately:',
    options: ['$500-$1,000', '$8,000-$27,000', '$100-$300', '$50,000+'],
    correctIndex: 1,
    explanation: 'The original 1959 Barbie, especially the #1 Ponytail Barbie, sells for $8,000-$27,000 depending on condition!',
    category: 'toys',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'toy-2',
    question: 'The most valuable Beanie Baby ever sold went for:',
    options: ['$5,000', '$50,000', '$500,000', '$5 million'],
    correctIndex: 2,
    explanation: 'Princess Diana Beanie Baby reportedly sold for $500,000! Though most Beanie Babies aren\'t worth much today.',
    category: 'toys',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'toy-3',
    question: 'Vintage Star Wars figures from the 1970s-80s can be worth up to:',
    options: ['$100-$500', '$1,000-$5,000', '$10,000-$300,000', '$1 million+'],
    correctIndex: 2,
    explanation: 'Rare Star Wars figures, like the vinyl-cape Jawa or rocket-firing Boba Fett prototype, can fetch $10,000-$300,000!',
    category: 'toys',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'toy-4',
    question: 'An original Teddy Bear from 1900s by Steiff can sell for:',
    options: ['$500-$1,000', '$5,000-$20,000', '$50,000-$100,000', '$200,000+'],
    correctIndex: 3,
    explanation: 'Antique Steiff teddy bears from the early 1900s have sold for over $200,000 at auction!',
    category: 'toys',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'toy-5',
    question: 'Hot Wheels cars from 1968 can be worth:',
    options: ['$10-$50', '$100-$500', '$1,000-$5,000', '$10,000-$150,000'],
    correctIndex: 3,
    explanation: 'Rare 1968 Hot Wheels like the "Beach Bomb" prototype have sold for $72,000-$150,000!',
    category: 'toys',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'toy-6',
    question: 'Original G.I. Joe action figures from 1964 are worth:',
    options: ['$50-$200', '$500-$2,000', '$2,000-$6,000', '$10,000+'],
    correctIndex: 2,
    explanation: 'Original 1964 G.I. Joe figures in box regularly sell for $2,000-$6,000 to collectors.',
    category: 'toys',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'toy-7',
    question: 'The rarest LEGO set ever sold went for approximately:',
    options: ['$10,000', '$50,000', '$100,000', '$300,000+'],
    correctIndex: 2,
    explanation: 'Rare LEGO sets like the Ultimate Collector\'s Millennium Falcon have sold for over $100,000 sealed!',
    category: 'toys',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'toy-8',
    question: 'Vintage Cabbage Patch Kids from the 1980s can be worth:',
    options: ['$20-$100', '$100-$500', '$500-$2,000', '$5,000+'],
    correctIndex: 2,
    explanation: 'Original 1980s Cabbage Patch Kids in boxes can sell for $500-$2,000, with rare ones going higher!',
    category: 'toys',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'toy-9',
    question: 'A complete original Transformers G1 Optimus Prime sells for:',
    options: ['$100-$300', '$500-$1,500', '$2,000-$4,000', '$5,000+'],
    correctIndex: 2,
    explanation: 'Complete 1984 G1 Optimus Prime with box and accessories sells for $2,000-$4,000!',
    category: 'toys',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'toy-10',
    question: 'Original Pokémon card booster boxes from 1999 sell for:',
    options: ['$1,000-$5,000', '$10,000-$30,000', '$50,000-$100,000', '$200,000+'],
    correctIndex: 3,
    explanation: 'Sealed 1st Edition Pokémon booster boxes have sold for over $400,000 at auction!',
    category: 'toys',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'toy-11',
    question: 'Vintage model trains from Lionel (1950s) are worth:',
    options: ['$100-$500', '$500-$3,000', '$5,000-$20,000', '$50,000+'],
    correctIndex: 2,
    explanation: 'Rare Lionel train sets from the 1950s can sell for $5,000-$20,000 depending on completeness.',
    category: 'toys',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'toy-12',
    question: 'An original Easy-Bake Oven from 1963 is worth:',
    options: ['$50-$100', '$200-$500', '$500-$1,000', '$2,000+'],
    correctIndex: 2,
    explanation: 'The original turquoise 1963 Easy-Bake Oven in working condition can sell for $500-$1,000!',
    category: 'toys',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'toy-13',
    question: 'What percentage of toys appreciate in value over time?',
    options: ['5-10%', '15-25%', '30-40%', '50-60%'],
    correctIndex: 0,
    explanation: 'Only about 5-10% of toys actually appreciate significantly. Condition and rarity are key!',
    category: 'toys',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'toy-14',
    question: 'A sealed Furby from 1998 is worth approximately:',
    options: ['$10-$30', '$50-$200', '$300-$900', '$1,000+'],
    correctIndex: 2,
    explanation: 'Sealed original Furbies from 1998 sell for $300-$900, with rare colors worth more!',
    category: 'toys',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'toy-15',
    question: 'The most expensive action figure ever sold was:',
    options: ['G.I. Joe prototype', 'Star Wars Boba Fett', 'He-Man prototype', 'Batman original'],
    correctIndex: 1,
    explanation: 'A rocket-firing Boba Fett prototype sold for $236,000 - the most expensive action figure!',
    category: 'toys',
    difficulty: 'hard',
    points: 15,
  },

  // ============================================
  // TECHNOLOGY & ELECTRONICS (15 questions)
  // ============================================
  {
    id: 'tech-1',
    question: 'An original Apple-1 computer typically sells for:',
    options: ['$50,000-$100,000', '$400,000-$900,000', '$1-5 million', '$10,000-$50,000'],
    correctIndex: 1,
    explanation: 'Apple-1 computers, with only ~200 ever made, regularly sell for $400,000-$900,000 at auction!',
    category: 'tech',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'tech-2',
    question: 'Sealed original iPods in their packaging can sell for:',
    options: ['$50-$100', '$200-$500', '$1,000-$20,000', '$100-$200'],
    correctIndex: 2,
    explanation: 'First-generation iPods still sealed in original packaging have sold for $1,000-$20,000 to collectors!',
    category: 'tech',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'tech-3',
    question: 'Rare Nintendo video games have sold for as much as:',
    options: ['$10,000', '$100,000', '$500,000', '$2 million'],
    correctIndex: 3,
    explanation: 'A sealed copy of Super Mario Bros. sold for $2 million in 2021, making it the most expensive video game ever!',
    category: 'tech',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'tech-4',
    question: 'An original IBM PC from 1981 is worth:',
    options: ['$500-$1,000', '$2,000-$5,000', '$5,000-$15,000', '$20,000+'],
    correctIndex: 2,
    explanation: 'Complete original IBM PCs from 1981 with original software sell for $5,000-$15,000.',
    category: 'tech',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'tech-5',
    question: 'A sealed original iPhone from 2007 has sold for:',
    options: ['$5,000-$10,000', '$20,000-$40,000', '$50,000-$100,000', '$150,000+'],
    correctIndex: 2,
    explanation: 'A factory-sealed original 2007 iPhone sold for over $63,000 at auction in 2023!',
    category: 'tech',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'tech-6',
    question: 'Original Atari 2600 games can be worth up to:',
    options: ['$100-$500', '$1,000-$5,000', '$10,000-$33,000', '$50,000+'],
    correctIndex: 2,
    explanation: 'The rarest Atari game, "Air Raid," has sold for $33,400 - making it extremely valuable!',
    category: 'tech',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'tech-7',
    question: 'A working vintage Macintosh 128K is worth:',
    options: ['$500-$1,000', '$1,000-$3,000', '$3,000-$5,000', '$5,000-$10,000'],
    correctIndex: 2,
    explanation: 'The original Macintosh 128K from 1984 sells for $3,000-$5,000 in working condition.',
    category: 'tech',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'tech-8',
    question: 'Vintage calculators from HP in the 1970s sell for:',
    options: ['$50-$200', '$200-$1,000', '$1,000-$5,000', '$10,000+'],
    correctIndex: 2,
    explanation: 'The HP-35, the first scientific pocket calculator (1972), sells for $1,000-$5,000!',
    category: 'tech',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'tech-9',
    question: 'A complete Nintendo Entertainment System (1985) is worth:',
    options: ['$100-$300', '$300-$800', '$1,000-$3,000', '$5,000+'],
    correctIndex: 1,
    explanation: 'Complete NES systems with original box sell for $300-$800, with rare variants worth more.',
    category: 'tech',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'tech-10',
    question: 'Sony Walkman from 1979 (TPS-L2) is worth:',
    options: ['$100-$300', '$500-$1,500', '$2,000-$5,000', '$10,000+'],
    correctIndex: 2,
    explanation: 'The original Sony Walkman TPS-L2 from 1979 sells for $2,000-$5,000 in good condition!',
    category: 'tech',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'tech-11',
    question: 'Original Game Boy games can be worth up to:',
    options: ['$100-$500', '$1,000-$5,000', '$10,000-$25,000', '$50,000+'],
    correctIndex: 2,
    explanation: 'Rare sealed Game Boy games like Pokémon Red have sold for $10,000-$25,000!',
    category: 'tech',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'tech-12',
    question: 'A vintage Polaroid SX-70 camera is worth:',
    options: ['$50-$100', '$100-$300', '$300-$600', '$1,000+'],
    correctIndex: 2,
    explanation: 'Working Polaroid SX-70 cameras in good condition sell for $300-$600 to collectors.',
    category: 'tech',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'tech-13',
    question: 'The most expensive video game console ever sold was:',
    options: ['Gold Nintendo Wii', 'Diamond-encrusted PS5', 'Nintendo PlayStation prototype', 'Solid gold Xbox'],
    correctIndex: 2,
    explanation: 'The Nintendo PlayStation prototype (only one exists) sold for $360,000!',
    category: 'tech',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'tech-14',
    question: 'Vintage mechanical keyboards from IBM are worth:',
    options: ['$20-$50', '$50-$150', '$150-$400', '$500+'],
    correctIndex: 2,
    explanation: 'IBM Model M keyboards from the 1980s-90s sell for $150-$400 and are prized by enthusiasts!',
    category: 'tech',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'tech-15',
    question: 'A sealed copy of Nintendo World Championships 1990 sold for:',
    options: ['$50,000', '$100,000', '$200,000', '$500,000+'],
    correctIndex: 2,
    explanation: 'The ultra-rare Nintendo World Championships cartridge sold for $230,000!',
    category: 'tech',
    difficulty: 'hard',
    points: 15,
  },

  // ============================================
  // ART & ANTIQUES (15 questions)
  // ============================================
  {
    id: 'art-1',
    question: 'A painting bought at a thrift store for $4 turned out to be worth:',
    options: ['$400', '$4,000', '$400,000', '$1 million+'],
    correctIndex: 3,
    explanation: 'Multiple thrift store paintings have been discovered to be worth millions - including lost works by famous artists!',
    category: 'art',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'art-2',
    question: 'Vintage movie posters from the 1930s-50s can sell for up to:',
    options: ['$1,000-$5,000', '$10,000-$50,000', '$100,000-$500,000', '$50-$500'],
    correctIndex: 2,
    explanation: 'Rare movie posters, especially for classics like Dracula or Metropolis, have sold for $100,000-$500,000!',
    category: 'art',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'art-3',
    question: 'Tiffany lamps from the early 1900s sell for:',
    options: ['$5,000-$20,000', '$50,000-$200,000', '$500,000-$3 million', '$1,000-$5,000'],
    correctIndex: 2,
    explanation: 'Authentic Tiffany lamps regularly sell for $500,000-$3 million at major auctions!',
    category: 'art',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'art-4',
    question: 'A single baseball card (1909 Honus Wagner) sold for:',
    options: ['$1 million', '$3.7 million', '$6.6 million', '$12 million'],
    correctIndex: 2,
    explanation: 'The T206 Honus Wagner card sold for $6.6 million in 2021 - the most expensive sports card!',
    category: 'art',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'art-5',
    question: 'Antique Persian rugs from the 17th century sell for:',
    options: ['$10,000-$50,000', '$100,000-$500,000', '$1 million-$10 million', '$20 million+'],
    correctIndex: 2,
    explanation: 'Rare antique Persian rugs have sold for $1-10 million at auction. Some fetch even more!',
    category: 'art',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'art-6',
    question: 'Original concert posters from the 1960s (Grateful Dead, etc.) are worth:',
    options: ['$100-$500', '$500-$5,000', '$5,000-$50,000', '$100,000+'],
    correctIndex: 2,
    explanation: 'Original 1960s concert posters from iconic bands sell for $5,000-$50,000!',
    category: 'art',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'art-7',
    question: 'A genuine Fabergé egg is valued at approximately:',
    options: ['$500,000-$2 million', '$5 million-$15 million', '$20 million-$40 million', '$50 million+'],
    correctIndex: 2,
    explanation: 'Authentic Fabergé Imperial eggs are valued at $20-40 million. Only 50 were ever made!',
    category: 'art',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'art-8',
    question: 'Vintage advertising signs from the early 1900s sell for:',
    options: ['$100-$500', '$500-$5,000', '$5,000-$50,000', '$100,000+'],
    correctIndex: 2,
    explanation: 'Porcelain enamel advertising signs from the early 1900s regularly sell for $5,000-$50,000!',
    category: 'art',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'art-9',
    question: 'Original Banksy artwork has sold for up to:',
    options: ['$500,000', '$5 million', '$15 million', '$25 million'],
    correctIndex: 3,
    explanation: 'Banksy\'s "Love is in the Bin" sold for $25.4 million in 2021 - his record price!',
    category: 'art',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'art-10',
    question: 'Antique Chinese porcelain vases have sold for:',
    options: ['$100,000-$500,000', '$1 million-$10 million', '$20 million-$50 million', '$80 million+'],
    correctIndex: 3,
    explanation: 'A Qianlong-era vase sold for $83 million! Chinese porcelain is extremely valuable.',
    category: 'art',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'art-11',
    question: 'Victorian-era jewelry with genuine gems is typically worth:',
    options: ['$500-$2,000', '$2,000-$10,000', '$10,000-$100,000', '$200,000+'],
    correctIndex: 2,
    explanation: 'Fine Victorian jewelry with quality gemstones regularly sells for $10,000-$100,000.',
    category: 'art',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'art-12',
    question: 'A signed photograph by a famous person is worth on average:',
    options: ['$50-$200', '$200-$1,000', '$1,000-$10,000', 'Varies by 100x+'],
    correctIndex: 3,
    explanation: 'Value varies enormously - Abraham Lincoln signatures fetch $100,000+, while modern signatures may be $50.',
    category: 'art',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'art-13',
    question: 'Original animation cels from Disney films sell for:',
    options: ['$500-$2,000', '$2,000-$10,000', '$10,000-$100,000', '$500,000+'],
    correctIndex: 2,
    explanation: 'Original Disney animation cels from classic films sell for $10,000-$100,000!',
    category: 'art',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'art-14',
    question: 'Antique clocks from the 1700s can be worth:',
    options: ['$1,000-$5,000', '$5,000-$30,000', '$30,000-$500,000', '$1 million+'],
    correctIndex: 2,
    explanation: 'Fine antique clocks from the 1700s by notable makers sell for $30,000-$500,000.',
    category: 'art',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'art-15',
    question: 'Art Deco furniture from the 1920s-30s is worth:',
    options: ['$500-$2,000', '$2,000-$10,000', '$10,000-$100,000', '$200,000+'],
    correctIndex: 2,
    explanation: 'Quality Art Deco furniture pieces sell for $10,000-$100,000. Some pieces exceed $500,000!',
    category: 'art',
    difficulty: 'medium',
    points: 10,
  },

  // ============================================
  // COINS & CURRENCY (12 questions)
  // ============================================
  {
    id: 'coin-1',
    question: 'The most expensive coin ever sold went for approximately:',
    options: ['$1 million', '$5 million', '$10 million', '$19 million'],
    correctIndex: 3,
    explanation: 'A 1933 Double Eagle gold coin sold for $18.9 million in 2021 - the most expensive coin ever!',
    category: 'coins',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'coin-2',
    question: 'A rare 1943 copper penny (instead of steel) is worth:',
    options: ['$100-$500', '$1,000-$5,000', '$10,000-$50,000', '$100,000-$1 million'],
    correctIndex: 3,
    explanation: '1943 copper pennies (minted by mistake in steel shortage year) are worth $100,000-$1 million!',
    category: 'coins',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'coin-3',
    question: 'A 1794 Flowing Hair Silver Dollar sold for:',
    options: ['$1 million', '$5 million', '$10 million', '$15 million'],
    correctIndex: 2,
    explanation: 'The 1794 Flowing Hair Dollar, believed to be the first US silver dollar, sold for $10 million!',
    category: 'coins',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'coin-4',
    question: 'Error coins (minting mistakes) can be worth:',
    options: ['Face value only', '2-10x face value', '100-1000x face value', '10,000x+ face value'],
    correctIndex: 3,
    explanation: 'Dramatic minting errors can be worth 10,000x or more! A 1955 double-die penny is worth $1,800+.',
    category: 'coins',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'coin-5',
    question: 'Silver Morgan Dollars (1878-1921) are typically worth:',
    options: ['$10-$30', '$30-$100', '$100-$500', '$1,000+'],
    correctIndex: 1,
    explanation: 'Common Morgan Dollars sell for $30-$100, though rare dates can be worth thousands!',
    category: 'coins',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'coin-6',
    question: 'Ancient Roman coins can be worth:',
    options: ['$20-$100', '$100-$1,000', '$1,000-$50,000', 'All of the above'],
    correctIndex: 3,
    explanation: 'Roman coins range from $20 for common types to $50,000+ for rare emperors and types!',
    category: 'coins',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'coin-7',
    question: 'A 1913 Liberty Head Nickel is worth approximately:',
    options: ['$100,000', '$500,000', '$3-5 million', '$10 million+'],
    correctIndex: 2,
    explanation: 'Only 5 exist! The 1913 Liberty Head Nickel sold for $4.5 million in 2018.',
    category: 'coins',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'coin-8',
    question: 'Gold coins from shipwrecks are worth how much more than regular coins?',
    options: ['Same value', '10-20% premium', '50-200% premium', '500%+ premium'],
    correctIndex: 2,
    explanation: 'Shipwreck coins often command 50-200% premiums due to their historical provenance!',
    category: 'coins',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'coin-9',
    question: 'What makes a coin "proof" grade?',
    options: ['Made of pure gold', 'Specially struck for collectors', 'Over 100 years old', 'Found in original wrapper'],
    correctIndex: 1,
    explanation: 'Proof coins are specially struck with polished dies for collectors - they\'re mirror-like!',
    category: 'coins',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'coin-10',
    question: 'Buffalo nickels (1913-1938) in good condition are worth:',
    options: ['$1-$5', '$5-$50', '$50-$500', '$1,000+'],
    correctIndex: 1,
    explanation: 'Common Buffalo nickels sell for $5-$50, though key dates can be worth much more!',
    category: 'coins',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'coin-11',
    question: 'The 1804 Silver Dollar (known as "King of American Coins") is worth:',
    options: ['$500,000', '$1 million', '$3-4 million', '$5 million+'],
    correctIndex: 2,
    explanation: 'The legendary 1804 Silver Dollar has sold for $3-4 million. Only 15 are known to exist!',
    category: 'coins',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'coin-12',
    question: 'Rare paper currency (like a $10,000 bill) can be worth:',
    options: ['Face value', '$15,000-$30,000', '$50,000-$200,000', '$500,000+'],
    correctIndex: 2,
    explanation: 'Rare $10,000 bills (discontinued in 1969) sell for $50,000-$200,000 to collectors!',
    category: 'coins',
    difficulty: 'hard',
    points: 15,
  },

  // ============================================
  // FASHION & CLOTHING (12 questions)
  // ============================================
  {
    id: 'fashion-1',
    question: 'Vintage Levi\'s 501 jeans from the 1950s can sell for:',
    options: ['$500-$1,000', '$5,000-$100,000', '$100-$500', '$1,000-$3,000'],
    correctIndex: 1,
    explanation: 'Vintage Levi\'s 501s from the 1950s are highly collectible, with rare pairs selling for $5,000-$100,000!',
    category: 'fashion',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'fashion-2',
    question: 'Original Air Jordan 1 sneakers from 1985 can be worth:',
    options: ['$500-$1,000', '$1,000-$10,000', '$10,000-$50,000', '$100-$500'],
    correctIndex: 2,
    explanation: 'Original 1985 Air Jordan 1s in good condition regularly sell for $10,000-$50,000 to sneaker collectors!',
    category: 'fashion',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'fashion-3',
    question: 'A vintage Hermès Birkin bag can sell for:',
    options: ['$5,000-$15,000', '$20,000-$100,000', '$100,000-$500,000', '$1 million+'],
    correctIndex: 2,
    explanation: 'Rare Hermès Birkin bags have sold for over $379,000! Even used ones fetch $20,000+.',
    category: 'fashion',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'fashion-4',
    question: 'Vintage Chanel handbags from the 1990s are worth:',
    options: ['$1,000-$3,000', '$3,000-$10,000', '$10,000-$30,000', '$50,000+'],
    correctIndex: 1,
    explanation: 'Vintage Chanel bags from the 1990s typically sell for $3,000-$10,000 depending on style.',
    category: 'fashion',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'fashion-5',
    question: 'Original band t-shirts from the 1970s sell for:',
    options: ['$50-$200', '$200-$1,000', '$1,000-$10,000', '$20,000+'],
    correctIndex: 2,
    explanation: 'Original Led Zeppelin, Rolling Stones, and other vintage band tees sell for $1,000-$10,000!',
    category: 'fashion',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'fashion-6',
    question: 'A vintage Rolex Daytona "Paul Newman" sells for:',
    options: ['$50,000-$100,000', '$200,000-$500,000', '$500,000-$1 million', '$1 million-$20 million'],
    correctIndex: 3,
    explanation: 'Paul Newman Daytonas sell for $1-20 million! His personal watch sold for $17.8 million.',
    category: 'fashion',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'fashion-7',
    question: 'Original designer wedding dresses from famous designers retain:',
    options: ['10-20% of value', '30-50% of value', '50-80% of value', '100%+ of value'],
    correctIndex: 1,
    explanation: 'Most wedding dresses retain only 30-50% of original value, even from top designers.',
    category: 'fashion',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'fashion-8',
    question: 'Vintage cowboy boots from the 1950s can be worth:',
    options: ['$100-$300', '$300-$1,000', '$1,000-$5,000', '$10,000+'],
    correctIndex: 2,
    explanation: 'Quality vintage cowboy boots from the 1950s sell for $1,000-$5,000 to collectors!',
    category: 'fashion',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'fashion-9',
    question: 'A genuine Louis Vuitton trunk from the 1920s is worth:',
    options: ['$2,000-$5,000', '$5,000-$20,000', '$20,000-$100,000', '$150,000+'],
    correctIndex: 2,
    explanation: 'Antique Louis Vuitton trunks sell for $20,000-$100,000 depending on size and condition.',
    category: 'fashion',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'fashion-10',
    question: 'Military uniforms from WWII can be worth:',
    options: ['$100-$500', '$500-$5,000', '$5,000-$50,000', '$100,000+'],
    correctIndex: 1,
    explanation: 'WWII uniforms typically sell for $500-$5,000, with rare pieces worth much more.',
    category: 'fashion',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'fashion-11',
    question: 'Vintage Ray-Ban Wayfarer sunglasses from the 1960s are worth:',
    options: ['$50-$150', '$150-$500', '$500-$2,000', '$3,000+'],
    correctIndex: 2,
    explanation: 'Original 1960s Ray-Ban Wayfarers in good condition sell for $500-$2,000!',
    category: 'fashion',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'fashion-12',
    question: 'Designer handbags appreciate in value at what rate on average?',
    options: ['They don\'t - they depreciate', '2-5% per year', '10-15% per year', '20%+ per year'],
    correctIndex: 1,
    explanation: 'Select luxury handbags (Chanel, Hermès) appreciate 2-5% per year on average. Most depreciate.',
    category: 'fashion',
    difficulty: 'easy',
    points: 5,
  },

  // ============================================
  // WATCHES (10 questions) - NEW CATEGORY
  // ============================================
  {
    id: 'watch-1',
    question: 'A vintage Rolex Submariner from the 1960s is worth:',
    options: ['$5,000-$15,000', '$15,000-$50,000', '$50,000-$200,000', '$300,000+'],
    correctIndex: 2,
    explanation: 'Vintage 1960s Rolex Submariners regularly sell for $50,000-$200,000 depending on reference.',
    category: 'watches',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'watch-2',
    question: 'The most expensive watch ever sold at auction went for:',
    options: ['$10 million', '$20 million', '$31 million', '$50 million'],
    correctIndex: 2,
    explanation: 'The Patek Philippe Grandmaster Chime sold for $31 million in 2019 - the most expensive watch!',
    category: 'watches',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'watch-3',
    question: 'A vintage Omega Speedmaster "Moonwatch" is worth:',
    options: ['$2,000-$5,000', '$5,000-$15,000', '$15,000-$50,000', '$100,000+'],
    correctIndex: 1,
    explanation: 'Vintage Omega Speedmasters typically sell for $5,000-$15,000, with rare refs worth more.',
    category: 'watches',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'watch-4',
    question: 'What dramatically increases a vintage watch\'s value?',
    options: ['New battery', 'Original box and papers', 'Recent polishing', 'Aftermarket dial'],
    correctIndex: 1,
    explanation: 'Original box and papers can add 20-50% to a vintage watch\'s value!',
    category: 'watches',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'watch-5',
    question: 'A Patek Philippe Nautilus from the 1970s sells for:',
    options: ['$20,000-$50,000', '$50,000-$150,000', '$150,000-$500,000', '$1 million+'],
    correctIndex: 2,
    explanation: 'Original Patek Philippe Nautilus 3700 watches sell for $150,000-$500,000!',
    category: 'watches',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'watch-6',
    question: 'Vintage Seiko watches from the 1960s-70s can be worth:',
    options: ['$100-$500', '$500-$3,000', '$5,000-$20,000', '$50,000+'],
    correctIndex: 1,
    explanation: 'Quality vintage Seikos sell for $500-$3,000, with rare models worth more!',
    category: 'watches',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'watch-7',
    question: 'A vintage Audemars Piguet Royal Oak from 1972 is worth:',
    options: ['$20,000-$50,000', '$50,000-$150,000', '$150,000-$400,000', '$500,000+'],
    correctIndex: 2,
    explanation: 'Original 1972 AP Royal Oak watches (ref. 5402) sell for $150,000-$400,000!',
    category: 'watches',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'watch-8',
    question: 'What percentage of luxury watches appreciate in value?',
    options: ['5-10%', '15-20%', '30-40%', '50%+'],
    correctIndex: 0,
    explanation: 'Only 5-10% of luxury watches actually appreciate. Most lose value after purchase!',
    category: 'watches',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'watch-9',
    question: 'A vintage Cartier Tank from the 1970s sells for:',
    options: ['$2,000-$5,000', '$5,000-$15,000', '$15,000-$40,000', '$50,000+'],
    correctIndex: 1,
    explanation: 'Vintage Cartier Tank watches from the 1970s typically sell for $5,000-$15,000.',
    category: 'watches',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'watch-10',
    question: 'The "tropical" dial on vintage watches refers to:',
    options: ['Made in tropics', 'Water resistance', 'Sun-faded color change', 'Palm tree design'],
    correctIndex: 2,
    explanation: 'Tropical dials are sun-faded to brown/chocolate - highly sought after and add significant value!',
    category: 'watches',
    difficulty: 'medium',
    points: 10,
  },

  // ============================================
  // SPORTS MEMORABILIA (8 questions) - NEW CATEGORY
  // ============================================
  {
    id: 'sports-1',
    question: 'A game-worn Michael Jordan jersey sold for:',
    options: ['$500,000', '$1.5 million', '$5 million', '$10.1 million'],
    correctIndex: 3,
    explanation: 'Jordan\'s 1998 "Last Dance" Finals jersey sold for $10.1 million - the most expensive sports memorabilia!',
    category: 'sports',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'sports-2',
    question: 'Original tickets to the first Super Bowl are worth:',
    options: ['$500-$2,000', '$2,000-$10,000', '$10,000-$50,000', '$100,000+'],
    correctIndex: 2,
    explanation: 'Original 1967 Super Bowl I tickets sell for $10,000-$50,000 depending on condition!',
    category: 'sports',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'sports-3',
    question: 'A baseball signed by Babe Ruth is worth approximately:',
    options: ['$5,000-$15,000', '$20,000-$50,000', '$50,000-$200,000', '$500,000+'],
    correctIndex: 1,
    explanation: 'Single-signed Babe Ruth baseballs typically sell for $20,000-$50,000.',
    category: 'sports',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'sports-4',
    question: 'A Mickey Mantle 1952 Topps card in mint condition sold for:',
    options: ['$1 million', '$5 million', '$12.6 million', '$20 million'],
    correctIndex: 2,
    explanation: 'A gem mint 1952 Topps Mickey Mantle sold for $12.6 million in 2022!',
    category: 'sports',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'sports-5',
    question: 'Vintage golf clubs from the early 1900s can be worth:',
    options: ['$100-$500', '$500-$5,000', '$5,000-$50,000', '$100,000+'],
    correctIndex: 2,
    explanation: 'Rare antique golf clubs, especially wooden clubs, sell for $5,000-$50,000!',
    category: 'sports',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'sports-6',
    question: 'A Muhammad Ali championship belt sold for:',
    options: ['$500,000', '$2 million', '$5 million', '$6.2 million'],
    correctIndex: 3,
    explanation: 'Ali\'s "Rumble in the Jungle" championship belt sold for $6.2 million!',
    category: 'sports',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'sports-7',
    question: 'Original Olympics memorabilia from 1896 can be worth:',
    options: ['$1,000-$5,000', '$10,000-$50,000', '$50,000-$200,000', '$500,000+'],
    correctIndex: 2,
    explanation: 'Medals and programs from the first modern Olympics (1896) sell for $50,000-$200,000!',
    category: 'sports',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'sports-8',
    question: 'A LeBron James rookie card in gem mint condition sold for:',
    options: ['$500,000', '$1.8 million', '$5.2 million', '$10 million'],
    correctIndex: 2,
    explanation: 'A 2003 LeBron James rookie card sold for $5.2 million in 2021!',
    category: 'sports',
    difficulty: 'hard',
    points: 15,
  },

  // ============================================
  // MUSIC & INSTRUMENTS (8 questions) - NEW CATEGORY
  // ============================================
  {
    id: 'music-1',
    question: 'A vintage Gibson Les Paul Standard from 1959 sells for:',
    options: ['$50,000-$100,000', '$100,000-$300,000', '$300,000-$500,000', '$500,000+'],
    correctIndex: 2,
    explanation: 'The 1959 Gibson Les Paul is the holy grail of guitars - worth $300,000-$500,000!',
    category: 'music',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'music-2',
    question: 'Original vinyl records from the 1950s in mint condition sell for:',
    options: ['$20-$100', '$100-$1,000', '$1,000-$50,000', '$100,000+'],
    correctIndex: 2,
    explanation: 'Rare original vinyl pressings can sell for $1,000-$50,000. Some exceed $100,000!',
    category: 'music',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'music-3',
    question: 'A Stradivarius violin is worth approximately:',
    options: ['$500,000-$1 million', '$2 million-$5 million', '$5 million-$16 million', '$20 million+'],
    correctIndex: 2,
    explanation: 'Stradivarius violins sell for $5-16 million. Only about 650 survive today!',
    category: 'music',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'music-4',
    question: 'A vintage Fender Stratocaster from 1954 is worth:',
    options: ['$20,000-$50,000', '$50,000-$100,000', '$100,000-$250,000', '$300,000+'],
    correctIndex: 2,
    explanation: 'Original 1954 Fender Stratocasters sell for $100,000-$250,000!',
    category: 'music',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'music-5',
    question: 'The Beatles\' "White Album" with serial number 0000001 sold for:',
    options: ['$50,000', '$200,000', '$790,000', '$1.5 million'],
    correctIndex: 2,
    explanation: 'Ringo Starr\'s copy (#0000001) of The White Album sold for $790,000!',
    category: 'music',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'music-6',
    question: 'Original concert posters from Elvis Presley shows sell for:',
    options: ['$500-$2,000', '$2,000-$10,000', '$10,000-$50,000', '$100,000+'],
    correctIndex: 2,
    explanation: 'Original Elvis concert posters from the 1950s-70s sell for $10,000-$50,000!',
    category: 'music',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'music-7',
    question: 'Vintage tube amplifiers from the 1960s can be worth:',
    options: ['$500-$2,000', '$2,000-$10,000', '$10,000-$50,000', '$100,000+'],
    correctIndex: 2,
    explanation: 'Rare vintage amps (Marshall, Fender) can sell for $10,000-$50,000!',
    category: 'music',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'music-8',
    question: 'Kurt Cobain\'s MTV Unplugged guitar sold for:',
    options: ['$1 million', '$3 million', '$6 million', '$10 million'],
    correctIndex: 2,
    explanation: 'Kurt Cobain\'s 1959 Martin D-18E sold for $6 million in 2020!',
    category: 'music',
    difficulty: 'hard',
    points: 15,
  },

  // ============================================
  // GENERAL KNOWLEDGE (15 questions)
  // ============================================
  {
    id: 'general-1',
    question: 'What percentage of people have at least one $500+ item they don\'t know about?',
    options: ['10%', '30%', '50%', '90%'],
    correctIndex: 3,
    explanation: 'Studies suggest 90% of households have at least one valuable item they don\'t realize is worth $500+!',
    category: 'general',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'general-2',
    question: 'The average American household has approximately how much in unused valuables?',
    options: ['$500', '$1,500', '$4,000', '$10,000'],
    correctIndex: 2,
    explanation: 'Research shows the average American household has about $4,000 in unused valuables collecting dust!',
    category: 'general',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'general-3',
    question: 'Items in original packaging are typically worth how much more?',
    options: ['10-20% more', '50-100% more', '2-5x more', '10x more'],
    correctIndex: 2,
    explanation: 'Items in original, unopened packaging often sell for 2-5x more than the same item without packaging!',
    category: 'general',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'general-4',
    question: 'The vintage Pyrex "Lucky in Love" pattern sells for approximately:',
    options: ['$50-$100', '$200-$500', '$1,000-$2,000', '$3,000-$4,000'],
    correctIndex: 3,
    explanation: 'The rare Pyrex "Lucky in Love" pattern with hearts can sell for $3,000-$4,000 to collectors!',
    category: 'general',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'general-5',
    question: 'What fraction of garage sale items is estimated to be worth $10,000+?',
    options: ['1 in 1,000', '1 in 10,000', '1 in 100,000', '1 in 1,000,000'],
    correctIndex: 2,
    explanation: 'Approximately 1 in every 100,000 garage sale items is estimated to be worth $10,000 or more!',
    category: 'general',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'general-6',
    question: 'What\'s the most common mistake that destroys collectible value?',
    options: ['Storing in attic', 'Cleaning/polishing', 'Taking photos', 'Moving items'],
    correctIndex: 1,
    explanation: 'Cleaning or polishing can destroy patina and original finish, dramatically reducing value!',
    category: 'general',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'general-7',
    question: 'The resale market for secondhand goods is worth approximately:',
    options: ['$50 billion', '$100 billion', '$200 billion', '$500 billion+'],
    correctIndex: 2,
    explanation: 'The global resale market is worth over $200 billion and growing 25% annually!',
    category: 'general',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'general-8',
    question: 'Which decade\'s items are currently most sought after by collectors?',
    options: ['1950s', '1970s', '1980s-90s', '2000s'],
    correctIndex: 2,
    explanation: 'Items from the 1980s-90s are hot right now as millennials collect their childhood nostalgia!',
    category: 'general',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'general-9',
    question: 'Storage Wars-style storage units contain valuable items what percentage of the time?',
    options: ['5-10%', '15-25%', '30-40%', '50%+'],
    correctIndex: 1,
    explanation: 'About 15-25% of abandoned storage units contain items worth more than the auction price!',
    category: 'general',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'general-10',
    question: 'Cast iron cookware from the late 1800s can be worth:',
    options: ['$50-$100', '$100-$500', '$500-$5,000', '$10,000+'],
    correctIndex: 2,
    explanation: 'Rare antique cast iron (like Griswold or Wagner) sells for $500-$5,000!',
    category: 'general',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'general-11',
    question: 'Vintage Fiestaware (1936-1973) is worth:',
    options: ['$10-$50', '$50-$200', '$200-$1,000', '$2,000+'],
    correctIndex: 2,
    explanation: 'Original Fiestaware pieces sell for $200-$1,000, with rare colors worth even more!',
    category: 'general',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'general-12',
    question: 'A first-generation iPhone still sealed has sold for:',
    options: ['$10,000', '$30,000', '$63,000', '$100,000+'],
    correctIndex: 2,
    explanation: 'A sealed 2007 iPhone sold for $63,000 at auction in 2023!',
    category: 'general',
    difficulty: 'hard',
    points: 15,
  },
  {
    id: 'general-13',
    question: 'The estate sale industry is worth approximately:',
    options: ['$1 billion', '$5 billion', '$17 billion', '$50 billion'],
    correctIndex: 2,
    explanation: 'The estate sale industry is worth about $17 billion annually in the US alone!',
    category: 'general',
    difficulty: 'medium',
    points: 10,
  },
  {
    id: 'general-14',
    question: 'What\'s the best time of year to find valuable items at garage sales?',
    options: ['Spring (March-April)', 'Summer (June-July)', 'Fall (September-October)', 'Winter (December)'],
    correctIndex: 0,
    explanation: 'Spring cleaning season (March-April) means more items and better finds at sales!',
    category: 'general',
    difficulty: 'easy',
    points: 5,
  },
  {
    id: 'general-15',
    question: 'Old Christmas ornaments from the 1950s can be worth:',
    options: ['$5-$20', '$20-$100', '$100-$500', '$1,000+'],
    correctIndex: 2,
    explanation: 'Vintage glass Christmas ornaments from the 1950s sell for $100-$500, with rare ones worth more!',
    category: 'general',
    difficulty: 'medium',
    points: 10,
  },
];

// Get random questions (shuffles and returns requested count)
export function getRandomQuestions(count: number): TriviaQuestion[] {
  const shuffled = [...triviaQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, triviaQuestions.length));
}

// Get questions by category
export function getQuestionsByCategory(category: TriviaQuestion['category'], count: number): TriviaQuestion[] {
  const filtered = triviaQuestions.filter(q => q.category === category);
  const shuffled = filtered.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, filtered.length));
}

// Get a single random question
export function getRandomQuestion(): TriviaQuestion {
  return triviaQuestions[Math.floor(Math.random() * triviaQuestions.length)];
}

// Get a random question that hasn't been asked yet
export function getRandomQuestionExcluding(excludeIds: string[]): TriviaQuestion | null {
  const available = triviaQuestions.filter(q => !excludeIds.includes(q.id));
  if (available.length === 0) return null;
  return available[Math.floor(Math.random() * available.length)];
}
