import { Metadata } from 'next';
import Link from 'next/link';
import { Footer } from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Disclaimer | RealWorth.ai',
  description: 'Important disclaimer about RealWorth.ai AI-generated appraisals and valuations.',
};

export default function DisclaimerPage() {
  return (
    <>
      <header className="bg-white border-b border-slate-200">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <Link href="/" className="text-xl font-bold text-teal-600 hover:text-teal-700">
            RealWorth.ai
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Disclaimer</h1>
        <p className="text-slate-500 text-sm mb-8">Last updated: December 5, 2025</p>

        {/* Important Notice Box */}
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-8">
          <h2 className="text-lg font-bold text-amber-800 mb-3">Important Notice</h2>
          <p className="text-amber-900 font-medium">
            All valuations provided by RealWorth.ai are <strong>AI-generated estimates</strong> for{' '}
            <strong>informational and entertainment purposes only</strong>. They do not constitute
            professional appraisals, certifications, authentication, or guarantees of market value.
          </p>
        </div>

        <div className="prose prose-slate max-w-none">
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-800 mb-3">1. Nature of Our Service</h2>
            <p className="text-slate-600 mb-4">
              RealWorth.ai uses artificial intelligence (AI) technology to analyze images of items and
              provide estimated value ranges. Our estimates are generated by machine learning models
              trained on publicly available market data and are intended to give you a general sense
              of what similar items may be worth.
            </p>
            <p className="text-slate-600 mb-4 font-medium">
              Our Service is <u>not</u> a substitute for professional appraisal services, and our
              estimates should <u>not</u> be relied upon for:
            </p>
            <ul className="list-disc list-inside text-slate-600 mb-4 space-y-1">
              <li>Insurance purposes or claims</li>
              <li>Estate planning or probate</li>
              <li>Tax purposes or charitable donations</li>
              <li>Legal proceedings or disputes</li>
              <li>Investment decisions</li>
              <li>Buying or selling decisions</li>
              <li>Authentication or provenance verification</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-800 mb-3">2. No Guarantee of Accuracy</h2>
            <p className="text-slate-600 mb-4">
              While we strive to provide helpful estimates, <strong>we make no guarantees regarding
              the accuracy, completeness, or reliability of our valuations</strong>. Actual market
              values can vary significantly based on factors including but not limited to:
            </p>
            <ul className="list-disc list-inside text-slate-600 mb-4 space-y-1">
              <li>Physical condition and authenticity of the item</li>
              <li>Provenance and historical significance</li>
              <li>Current market conditions and demand</li>
              <li>Geographic location and local markets</li>
              <li>Timing of sale and market fluctuations</li>
              <li>Rarity and availability of similar items</li>
              <li>Quality of images provided for analysis</li>
            </ul>
            <p className="text-slate-600 mb-4">
              Our AI cannot physically inspect items, verify authenticity, or account for conditions
              not visible in photographs.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-800 mb-3">3. Not Professional Advice</h2>
            <p className="text-slate-600 mb-4">
              The information provided by RealWorth.ai does not constitute:
            </p>
            <ul className="list-disc list-inside text-slate-600 mb-4 space-y-1">
              <li>Professional appraisal services</li>
              <li>Financial or investment advice</li>
              <li>Legal advice</li>
              <li>Tax advice</li>
              <li>Insurance advice</li>
              <li>Authentication or certification services</li>
            </ul>
            <p className="text-slate-600 mb-4">
              For matters requiring professional appraisal, please consult a certified appraiser,
              financial advisor, attorney, or other qualified professional.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-800 mb-3">4. User Responsibility</h2>
            <p className="text-slate-600 mb-4">
              By using RealWorth.ai, you acknowledge and agree that:
            </p>
            <ul className="list-disc list-inside text-slate-600 mb-4 space-y-1">
              <li>You use our estimates at your own risk</li>
              <li>You are solely responsible for any decisions made based on our estimates</li>
              <li>You will seek professional advice for important financial or legal matters</li>
              <li>You understand our estimates may differ significantly from actual market values</li>
              <li>You will not hold RealWorth.ai liable for any losses resulting from reliance on our estimates</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-800 mb-3">5. Limitation of Liability</h2>
            <p className="text-slate-600 mb-4">
              TO THE FULLEST EXTENT PERMITTED BY LAW, REALWORTH.AI, ITS OWNERS, EMPLOYEES, AGENTS,
              AND AFFILIATES SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR EXEMPLARY DAMAGES ARISING FROM OR RELATED TO:
            </p>
            <ul className="list-disc list-inside text-slate-600 mb-4 space-y-1">
              <li>Your use of or reliance on our valuations or estimates</li>
              <li>Any buying, selling, or holding decisions based on our Service</li>
              <li>Differences between our estimates and actual market values</li>
              <li>Loss of profit, revenue, data, or business opportunities</li>
              <li>Any other damages arising from your use of the Service</li>
            </ul>
            <p className="text-slate-600 mb-4">
              This limitation applies regardless of the theory of liability, including breach of
              contract, tort (including negligence), strict liability, or any other legal theory.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-800 mb-3">6. Third-Party Content</h2>
            <p className="text-slate-600 mb-4">
              Our Service may reference or link to third-party websites, marketplaces, or data sources.
              We are not responsible for the accuracy, reliability, or content of any third-party
              information. Reference prices from external sources are provided for context only and
              may not reflect current market conditions.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-800 mb-3">7. Changes to This Disclaimer</h2>
            <p className="text-slate-600 mb-4">
              We reserve the right to modify this Disclaimer at any time. Changes will be effective
              immediately upon posting to this page. Your continued use of the Service after any
              changes indicates your acceptance of the modified Disclaimer.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-slate-800 mb-3">8. Contact Us</h2>
            <p className="text-slate-600 mb-4">
              If you have questions about this Disclaimer, please contact us at:{' '}
              <a href="mailto:support@realworth.ai" className="text-teal-600 hover:text-teal-700 underline">
                support@realworth.ai
              </a>
            </p>
          </section>
        </div>

        {/* Summary Box */}
        <div className="bg-slate-100 border border-slate-200 rounded-xl p-6 mt-8">
          <h2 className="text-lg font-bold text-slate-800 mb-3">Summary</h2>
          <p className="text-slate-700">
            RealWorth.ai provides AI-generated estimates for fun and informational purposes.
            For important decisions involving valuable items, always consult qualified professionals.
            Use our Service responsibly and at your own risk.
          </p>
        </div>
      </main>

      <Footer />
    </>
  );
}
